apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dp
  labels:
    type: frontend
spec:
  template:
    metadata:
      labels:
        app: frontend
        type: frontend
    spec:
      containers:
        - name: nginx-container
          image: nginx
  selector:
    matchLabels:
      type: frontend
  replicas: 6